server:
  port: 8080
spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true # Permite achar serviços pelo nome no Eureka
          routes:
            - id: sensor-route
              uri: lb://SENSOR-SERVICE # 'lb' ativa o Load Balancer do Eureka
              predicates:
                - Path=/sensor/**
              filters:
                - StripPrefix=1 # Remove o '/sensor' da URL antes de mandar pro micro
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
